---
fullname: Record Update
shortname: record-update
organization: tchajed
community: false
travis: true
coqdoc: false

synopsis: >-
  Generic support for updating record fields

description: |-
  While Coq provides projections for each field of a record, it has no
  convenient way to update a single field of a record. This library provides a
  generic way to update a field by name, where the user only has to implement a
  simple typeclass that lists out the record fields.

authors:
- name: Tej Chajed
  initial: true

maintainers:
- name: Tej Chajed
  nickname: tchajed

opam-file-maintainer: tchajed@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT
  file: LICENSE

supported_coq_versions:
  text: 8.8 or later
  opam: '{(>= "8.8" & < "8.13~") | (= "dev")}'

tested_coq_opam_versions:
- version: dev
- version: '8.12'
- version: '8.11'
- version: '8.10'
- version: '8.9'
- version: '8.8'

dependencies:
- description: none
namespace: RecordUpdate

keywords:
- name: record

categories:
- name: Computer Science/Data Types and Data Structures
---
